### ISSUE TITLE
Rewrite formatter of code for location of error

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly#139]
Currently, I use a custom function to extract a few lines of code around the line causing a problem, and use Pygment/Rich to do syntax highlighting.  I use the exact same function for both SyntaxError cases and for general runtime errors (NameError, TypeError, etc.).  There are a few problems with the approach I use, problems that appear to be nicely avoided by https://github.com/alexmojaki/stack_data when dealing with runtime errors.  Basically, instead of working with individual lines of code, stack_data can extract individual "pieces of code" which essentially correspond to statements.  This avoids some problems that a line-based approach can cause. 

Let's start with an example that works well with the current approach I use, where we have a traceback that involves 3 frames of "user code":
![image](https://user-images.githubusercontent.com/629698/103534594-8f6ed180-4e65-11eb-9567-1e47c9d8cf2d.png)

By "user code" I mean code that does not include frames from Friendly-traceback itself.

Here's the more detailed information obtained about the cause of the error.

![image](https://user-images.githubusercontent.com/629698/103532920-86c8cc00-4e62-11eb-8546-f48b9e504f94.png)

We see the original call, with information about the values of the variables that appear on the line of code that started the problem. Initially I was showing the information about all the names shown in that code sample, but determined that this was sometimes too much information that was not relevant (more on this below).

We also see the information about the values of the variables that actually caused the problem. Here, we used https://github.com/alexmojaki/executing to focus only on the "node" that caused the problem, showing only the relevant variables. This works rather nicely.

When the problematic statement spreads over two lines, we still see the relevant lines of code and values of variables, without the extra highlighting by `^^^`.
![image](https://user-images.githubusercontent.com/629698/103533684-f095a580-4e63-11eb-87eb-b6ff990ba001.png)

However, if the problematic statement spreads over more than two lines, we no longer see the relevant variables, but still see the information about all the relevant values, which could definitely be confusing.
![image](https://user-images.githubusercontent.com/629698/103533773-1cb12680-4e64-11eb-8e70-283e11646338.png)

Furthermore, if it happens that the first line displayed is the end of a triple quoted string, we lose the syntax highlighting as the whole code sample is treated as though it was part of a triple quoted string.

![image](https://user-images.githubusercontent.com/629698/103533871-44a08a00-4e64-11eb-9df6-3a79deb02448.png)

By working with "pieces of code", stack_data would help avoid these problems entirely. However, since I'm often dealing with a situation like the following:

- frame 1: friendly-traceback code
- frame 2: user code
- ...
- frame n: user code
- frame n+1 : friendly-traceback code
- etc.
I would need to reliably identify frames 2 and "n" using stack_data.  My early attempts did not work, but that was very likely due to my own misunderstanding.

When working with SyntaxError cases, all of the above problems can also surface. Here however, stack_data can not help us as it cannot parse syntactically invalid code and identify relevant "pieces of code".  Since we don't have to worry about showing the relevant variable values, some of the problem mentioned above can be ignored. The "docstring" problem can however be present. I have started working on a heuristic method to isolate would-be statements/"pieces of code" that works reasonably well. However, early attempts showed that I could not use the same formattting/hightlighting function for both runtime and SyntaxError cases ... which is perfectely fine. 

So, I need to take care of these cases separately. Since this will likely involve multiple commits, I've created this issue as a reference for the work to be done.

**Comment by alexmojaki** [comment]
Would you like some help with stack_data?

I notice some code that expects to be able to parse a single line, which seems very relevant to this:

https://github.com/aroberge/friendly-traceback/blob/8e58b60dd884e291ca2e57b8cd4aef4e5c10c820/friendly/info_variables.py#L115-L118

**Comment by aroberge** [comment]
I definitely would welcome help on using stack_data.  The idea of going back and figuring out once and for all how to use it for runtime errors keeps preying on my mind, but I always find something "easier" to work on.

**Comment by alexmojaki** [comment]
Got any broken code or specific questions?

**Comment by aroberge** [comment]
No broken code as I do not use stack_data. 

In another issue (that I closed today) you had given me pointers on how to use it to identify the "final" frame, where the exception occurred (by passing the tb object instead of the frame object).  My remaining quandary is/was how to identify the "initial" frame, i.e. the one with the **user's code**.  If you recall, I remove from the traceback frames that come from my own code; so I need to "unwind" the traceback only until the initial frame from the user code is found.

For example, when using the friendly console, I have something like:
```
exec(user_code)  # this frame is my code
```
Python would point this line as the origin of the traceback; however, I do not want to include it. Using inspect, I can "clean up" and remove unwanted frames - but I am not sure yet on how to do it correctly with stack_data.  It's probably straightforward - I just did not invest enough time to explore it properly.

**Comment by alexmojaki** [comment]
It seems like replacing this line:

https://github.com/aroberge/friendly-traceback/blob/8e58b60dd884e291ca2e57b8cd4aef4e5c10c820/friendly/core.py#L100

with stack_data should work quite straightforwardly.

Comparing the two:

```python
import inspect
import stack_data

try:
    exec("1/0")
except Exception as e:
    tb = e.__traceback__
    for records in [
        stack_data.FrameInfo.stack_data(tb),
        inspect.getinnerframes(tb)
    ]:
        print([r.filename for r in records])
```

They both print the same thing.

**Comment by aroberge** [comment]
This has been taken care of since switching to using stack_data.
