### ISSUE TITLE
Rename GitHub repo

### ISSUE THREAD

**Issue by alexmojaki** [aroberge/friendly#196]
GitHub will automatically redirect URLs with the old repo name, e.g. https://github.com/alexmojaki/python_init/issues

Congrats on releasing 0.3.0! And thank you for backing futurecoder :smile:

**Comment by aroberge** [comment]
Thanks for 0.3, and you're welcome for futurecoder.

I knew about the automatic redirecting - just one more thing to take care of... Thanks for opening the issue
