### ISSUE TITLE
Errors from Cs Circles

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly#198]
List of errors from http://daveagp.github.io/errors/python.txt (see https://arxiv.org/pdf/1509.07238.pdf)
They have been obtained from users of https://cscircles.cemc.uwaterloo.ca/.

Explanations for the most common ones can be found in https://github.com/cemc/cscircles-wp-content/blob/master/plugins/pybox/plugin-errorhint-en_US.php

### Most common errors
- [x] SyntaxError: invalid syntax - occurred 179624 times
There are many, many cases of `SyntaxError: invalid syntax` that friendly already takes care of ... but there will always be more.
- [x] NameError: name '' is not defined - occurred 97186
- [x] EOFError: EOF when reading a line - occurred 76026

### The following occurred approximately between 10000 and 26000 times
- [x] SyntaxError: unexpected EOF while parsing
- [x] IndentationError: unindent does not match any outer indentation level
- [x] SyntaxError: EOL while scanning string literal
- [x] IndentationError: unexpected indent
- [x] TabError: inconsistent use of tabs and spaces in indentation
- [x] IndentationError: expected an indented block
- [ ] ValueError: invalid literal for func() with base #: ''
- [x] TypeError: '' object is not iterable

### The following occurred between 1000 and 10000 times
- [x] TypeError: '' object is not callable
- [x] TypeError: can't multiply sequence by non-int of type ''
- [x] TypeError: unsupported operand type(s) for +: '' and ''
- [ ] NameError: global name '' is not defined
       I have not been able to get this error message (with `global` in it); I suspect that this was specific to Python 2
- [x] TypeError: unsupported operand type(s) for -: '' and ''
- [x] IndexError: string index out of range
- [x] SyntaxError: unexpected character after line continuation character
- [ ] TypeError: Can't convert '' object to str implicitly
- [x] TypeError: unsupported operand type(s) for //: '' and ''
- [x] AttributeError: '' object has no attribute ''
- [x] TypeError: '' object is not subscriptable
- [ ] TypeError: string indices must be integers
- [x] IndexError: list index out of range
- [x] SyntaxError: can't assign to function call
- [x] UnboundLocalError: local variable '' referenced before assignment
- [x] SyntaxError: can't assign to operator
- [ ] ValueError: could not convert string to float: ''
- [ ] TypeError: unorderable types: func() > func()
- [ ] TypeError: not all arguments converted during string formatting
- [ ] TypeError: object of type '' has no func()
- [x] TypeError: '' object cannot be interpreted as an integer
- [x] TypeError: list indices must be integers, not <TYPE>
- [ ] TypeError: an integer is required
- [x] TypeError: unsupported operand type(s) for /: '' and ''
- [ ] TypeError: func() expected string of length #, but <TYPE> found
- [ ] RuntimeError: maximum recursion depth exceeded while calling a Python object
- [x] TypeError: unsupported operand type(s) for ** or func(): '' and ''
- [ ] IndexError: list assignment index out of range
- [x] TypeError: slice indices must be integers or None or have an __index__ method
- [ ] TypeError: unsupported operand type(s) for *: '' and ''
- [x] SyntaxError: break outside loop
- [ ] TypeError: func() expected a character, but string of length # found
- [x] SyntaxError: return outside function
- [x] SyntaxError: can't assign to literal
- [ ] TypeError: unorderable types: func() < func()
- [ ] ValueError: ? is not in list
- [ ] TypeError: func() argument must be a string or a number, not ''
- [x] TypeError: can only concatenate list (not "") to list
- [x] TypeError: '' object does not support item assignment
- [ ] ValueError: math domain error

### The following occurred between 500 and 1000 times
- [x] SyntaxError: invalid token
- [x] TypeError: func() takes exactly # arguments (# given)
- [ ] RuntimeError: maximum recursion depth exceeded in comparison
- [ ] TypeError: '' is an invalid keyword argument for this function
- [ ] TypeError: unorderable types: func() >= func()
- [x] SyntaxError: invalid character in identifier
- [x] TypeError: func() missing # required positional arguments: ''
- [ ] MemoryError
- [x] TypeError: bad operand type for unary +: ''
- [x] ZeroDivisionError: integer division or modulo by zero
- [x] SyntaxError: continue not properly in loop

### The following occurred between 100 and 500 times
- [x] TypeError: unsupported operand type(s) for ^: '' and ''
- [ ] TypeError: func() takes at least # arguments (# given)
- [ ] TypeError: bad operand type for unary -: ''
- [x] SyntaxError: keyword can't be an expression
- [ ] RuntimeError: maximum recursion depth exceeded
- [ ] TypeError: descriptor '' requires a '' object but received a ''
- [ ] TypeError: func() takes no arguments (# given)
- [ ] ValueError: list.remove(x): x not in list
- [x] ZeroDivisionError: division by zero
- [ ] TypeError: a float is required
- [ ] TypeError: func() argument must be a string or a number
- [ ] SyntaxError: can use starred expression only as assignment target
- [ ] TypeError: unorderable types: func() <= func()
- [ ] PermissionError: [Errno #] Permission denied: ''
- [ ] TypeError: func() takes # positional arguments but # were given
- [ ] TypeError: can only concatenate tuple (not "") to tuple
- [ ] TypeError: argument of type '' is not iterable
- [x] ImportError: No module named ''
- [ ] TypeError: unsupported operand type(s) for %: '' and ''
- [ ] SyntaxError: non-keyword arg after keyword arg
- [ ] TypeError: func() argument after * must be a sequence, not <TYPE>
- [x] TypeError: unsupported operand type(s) for +=: '' and ''
- [ ] TypeError: func() takes no keyword arguments
- [x] SyntaxError: EOF while scanning triple-quoted string literal
- [ ] ValueError: substring not found
- [x] TypeError: func() expected # arguments, got #
- [x] ZeroDivisionError: float division by zero
- [x] AttributeError: type object '' has no attribute ''
- [ ] IndexError: pop index out of range
- [x] TypeError: func() takes at most # arguments (# given)
- [ ] ValueError: func() arg is an empty sequence
- [x] TypeError: func() expected at most # arguments, got #
- [ ] ValueError: func() arg not in range(Ox#)

### The following occurred between 10 and 100 times

- [ ] TypeError: unsupported operand type(s) for &: '' and ''
- [x] IndexError: tuple index out of range
- [ ] TypeError: func() can't convert non-string with explicit base
- [x] SyntaxWarning: name '' is assigned to before global declaration
- [ ] BlockingIOError: [Errno #] Resource temporarily unavailable
- [ ] FileNotFoundError: [Errno #] No such file or directory: ''
- [ ] ValueError: could not convert string to float:
- [ ] TypeError: descriptor '' of '' object needs an argument
- [ ] ValueError: too many values to unpack (expected #)
- [ ] TypeError: '' requires string as left operand, not <TYPE>
- [x] SyntaxError: can't delete function call
- [x] SyntaxError: name '' is parameter and global
- [ ] TypeError: integer argument expected, got float
- [ ] TypeError: func() first arg must be str or a tuple of str, not <TYPE>
- [ ] TypeError: int object argument after * must be a sequence, not <TYPE>
- [ ] TypeError: func() argument # must be str, not <TYPE>
- [ ] ValueError: empty separator
- [ ] SyntaxError: can't assign to comparison
- [ ] TypeError: func() arg # must be a type or tuple of types
- [ ] ValueError: slice step cannot be zero
- [ ] AttributeError: '' object attribute '' is read-only
- [x] KeyError: ?
- [ ] TypeError: '' object doesn't support item deletion
- [ ] ImportError: No module named ''; math is not a package
- [ ] OverflowError: (#, 'Numerical result out of range')
- [ ] PermissionError: [Errno #] Operation not permitted
- [ ] ValueError: not allowed to raise maximum limit
- [ ] ValueError: need more than # value to unpack
- [ ] socket.gaierror: [Errno -#] Name or service not known
- [ ] TypeError: func() takes # or # arguments
- [ ] ValueError: func() arg # must be >= # and <= #
- [ ] TypeError: '' object does not support item deletion
- [ ] TypeError: decoding str is not supported
- [ ] UnicodeEncodeError: '' codec can't encode character '' in position #: surrogates not allowed
- [ ] TypeError: source code string cannot contain null bytes
- [ ] TypeError: func() got an unexpected keyword argument
- [x] SyntaxError: assignment to keyword
- [ ] TypeError: func() does not take keyword arguments
- [ ] TypeError: sequence item #: expected str instance, <TYPE> found
- [ ] SyntaxError: only named arguments may follow *expression
- [ ] ValueError: attempt to assign sequence of size # to extended slice of size #
- [ ] TypeError: bad operand type for func(): ''
- [x] SyntaxError: duplicate argument '' in function definition
- [ ] TypeError: (Raised by CS Circles) func() can only be applied to numbers
- [ ] TypeError: not enough arguments for format string
- [ ] TypeError: unsupported operand type(s) for |: '' and ''
- [ ] ValueError: func() arg # must not be zero
- [ ] ValueError: need more than # values to unpack
- [x] ZeroDivisionError: float modulo
- [ ] TypeError: func() expected at least # arguments, got #
- [ ] TypeError: unhashable type: ''
- [x] TypeError: unsupported operand type(s) for -=: '' and ''
- [ ] TypeError: must assign iterable to extended slice
- [ ] TypeError: Required argument '' (pos #) not found
- [ ] StderrExample
- [x] SyntaxError: keyword argument repeated
- [ ] TypeError: can only assign an iterable
- [ ] TypeError: must use keyword argument for key function
- [ ] TypeError: '' object does not support indexing
- [ ] TypeError: func() arg must be None or str
- [ ] ValueError: unsupported format character '' () at index #
- [ ] ImportError: cannot import name ?
- [ ] IndexError: range object index out of range
- [ ] SyntaxError: (unicode error) '' codec can't decode bytes in position #-#: truncated \\xXX escape
- [x] SyntaxError: can't delete literal
- [ ] TypeError: coercing to str: need bytes, bytearray or buffer-like object, <TYPE> found
- [ ] ZeroDivisionError: float func()
- [ ] NotADirectoryError: [Errno #] Not a directory: ''
- [ ] SyntaxError: illegal expression for augmented assignment
- [ ] SyntaxError: yield outside function
- [ ] TypeError: %d format: a number is required, not <TYPE>
- [ ] TypeError: __str__ returned non-string (type <TYPE>)
- [ ] TypeError: end must be None or a string, not <TYPE>
- [ ] TypeError: func() arg # must be a string, bytes or code object
- [ ] TypeError: type <TYPE> doesn't define ? method

### The following occurred less than 10 times
- [ ] TypeError: can't set attributes of built-in/extension type ''
- [ ] TypeError: string argument expected, got ''
- [x] ZeroDivisionError: #.# cannot be raised to a negative power
- [ ] AssertionError
- [ ] SyntaxError: (unicode error) '' codec can't decode bytes in position #-#: truncated \\uXXXX escape
- [ ] SyntaxWarning: name '' is used prior to global declaration
- [ ] AttributeError: __exit__
- [x] SyntaxError: can't assign to conditional expression
- [ ] TypeError: (Raised by CS Circles) func() can only be applied to non-negative integers
- [ ] TypeError: NoneType object argument after * must be a sequence, not <TYPE>
- [ ] TypeError: float object argument after * must be a sequence, not <TYPE>
- [ ] TypeError: unsupported operand type(s) for <<: '' and ''
- [ ] OSError: [Errno #] File too large
- [ ] SyntaxError: starred assignment target must be in a list or tuple
- [ ] TypeError: str object argument after * must be a sequence, not <TYPE>
- [ ] ValueError: Unknown format code '' for object of type ''
- [ ] PermissionError: [Errno #] Permission denied
- [ ] TypeError: The fill character cannot be converted to Unicode
- [ ] TypeError: expected # arguments, got #
- [ ] TypeError: type object argument after * must be a sequence, not <TYPE>
- [ ] ValueError: incomplete format
- [ ] socket.gaierror: [Errno -#] No address associated with hostname
- [ ] IndexError: pop from empty list
- [ ] OverflowError: long int too large to convert to float
- [ ] RuntimeError: maximum recursion depth exceeded while getting the repr of a list
- [ ] SyntaxError: (unicode error) '' codec can't decode bytes in position #-#: end of string in escape sequence
- [x] SyntaxError: can't assign to ()
- [ ] TypeError
- [ ] TypeError: can't convert complex to float
- [ ] TypeError: can't take floor of complex number.
- [ ] TypeError: must be bytes, not <TYPE>
- [ ] TypeError: unsupported operand type(s) for >>: '' and ''
- [ ] TypeError: unsupported operand type(s) for func(): '' and ''
- [ ] ValueError: Invalid format specifier
- [ ] ValueError: tuple.index(x): x not in tuple
- [ ] IndentationError: unexpected unindent
- [ ] IsADirectoryError: [Errno #] Is a directory: ''
- [ ] OSError: [Errno #] Function not implemented
- [ ] OverflowError: signed integer is greater than maximum
- [ ] SyntaxError: (unicode error) '' codec can't decode bytes in position #-#: truncated \\UXXXXXXXX escape
- [x] SyntaxError: Generator expression must be parenthesized if not sole argument
- [x] SyntaxError: can't delete ()
- [ ] SyntaxError: cannot mix bytes and nonbytes literals
- [ ] TypeError: %i format: a number is required, not <TYPE>
- [ ] TypeError: '' does not support the buffer interface
- [ ] TypeError: '' object is not an iterator
- [ ] TypeError: The fill character must be exactly one character long
- [ ] TypeError: can't convert complex to int
- [ ] TypeError: format requires a mapping
- [ ] TypeError: func() argument after ** must be a mapping, not <TYPE>
- [ ] TypeError: func() got an unexpected keyword argument ''
- [ ] TypeError: sep must be None or a string, not <TYPE>
- [ ] ValueError: could not convert string to float: ""
- [ ] __main__.BailOut
- [ ] NameError: free variable '' referenced before assignment in enclosing scope
- [ ] OverflowError: cannot fit '' into an index-sized integer
- [ ] OverflowError: math range error
- [ ] RuntimeError: can't start new thread
- [ ] RuntimeError: maximum recursion depth exceeded while getting the repr of a tuple
- [ ] StopIteration
- [ ] SyntaxError: (unicode error) '' codec can't decode bytes in position #-#: malformed \\N character escape
- [ ] SyntaxError: (unicode error) '' codec can't decode bytes in position #-#: unknown Unicode character name
- [x] SyntaxError: no binding for nonlocal '' found
- [ ] TypeError: bad operand type for unary ~: ''
- [ ] TypeError: func() can't sum strings [use ''.join(seq) instead]
- [ ] TypeError: object does not provide __dir__
- [ ] TypeError: tuple indices must be integers, not <TYPE>
- [ ] UnicodeEncodeError: '' codec can't encode characters in position #-#: ordinal not in range(#)
- [ ] ValueError: Unknown conversion specifier b
- [ ] ValueError: func() only accepts integral values
- [ ] urllib.error.URLError: <urlopen error [Errno -#] Name or service not known>

### The following occurred one time each
- [ ] AssertionError: You are mathing wrong
- [ ] FAILED (errors=#)
- [ ] FileNotFoundError: [Errno #] No such file or directory
- [ ] ImportError: No module named ''; datetime is not a package
- [ ] ImportError: No module named ''; random is not a package
- [ ] OSError: [Errno #] Address already in use
- [ ] OSError: out of pty devices
- [ ] ProcessLookupError: [Errno #] No such process
- [ ] RuntimeError: dictionary changed size during iteration
- [x] SyntaxError: can't assign to Ellipsis
- [ ] SyntaxError: can't delete operator
- [x] SyntaxError: from __future__ imports must occur at the beginning of the file
- [ ] TypeError: Input must be an integer.
- [ ] TypeError: Tuple or struct_time argument required
- [ ] TypeError: argument # must have a "" method
- [ ] TypeError: argument to func() must be a sequence
- [ ] TypeError: array item must be unicode character
- [ ] TypeError: bytes expected instead of str instance
- [ ] TypeError: cannot convert dictionary update sequence element ## to a sequence
- [ ] TypeError: expected string or buffer
- [ ] TypeError: func() argument # must be tuple, not <TYPE>
- [ ] TypeError: func() must have at least two arguments.
- [ ] TypeError: must be a unicode character, not <TYPE>
- [ ] TypeError: must be str, not <TYPE>
- [ ] TypeError: range indices must be integers or slices, not <TYPE>
- [ ] TypeError: str object argument after ** must be a mapping, not <TYPE>
- [ ] TypeError: string argument without an encoding
- [ ] TypeError: unsupported operand type(s) for *=: '' and ''
- [ ] TypeError: unsupported type for timedelta days component: str
- [ ] TypeError: zip argument ## must support iteration
- [ ] UnicodeDecodeError: '' codec can't decode byte Ox# in position #: invalid start byte
- [ ] ValueError: Format specifier missing precision
- [ ] ValueError: Nothing to see here!
- [ ] ValueError: Precision not allowed in integer format specifier
- [ ] ValueError: Sign not allowed in string format specifier
- [ ] ValueError: Single '' encountered in format string
- [ ] ValueError: dictionary update sequence element ## has length #; # is required
- [ ] ValueError: empty range for func() (#,#, -#)
- [ ] ValueError: func() not defined for negative values
- [ ] ValueError: unmatched '' in format
- [ ] mainfile: error: must provide name of pdb file
- [ ] sre_constants.error: redefinition of group name '' as group #; was group #

**Comment by alexmojaki** [comment]
Looks like you need a space after the dash.

**Comment by aroberge** [comment]
You are right; it's fixed now.

**Comment by aroberge** [comment]
Migrated to new repo.
