### ISSUE TITLE
unrecognized error in range(2,ceil(sqrt(n))

### ISSUE THREAD

**Issue by theneto97** [aroberge/friendly#204]
as asked here is an error unrecognized by friendly-traceback

here is the  message it get:

Exception Python
Traceback (most recent call last):
  File "solution.py", line 16, in <module>
    assert is_prime(4) is False
AssertionError:
Aucune information n’est connue à propos de cette exception. Veuillez signaler cet exemple à https://github.com/aroberge/friendly-traceback/issues
Si vous utilisez la console Friendly, utilisez www() pour faire une recherche sur Internet pour ce cas particulier

and here is the source code:

``` 
from math import sqrt, ceil

def is_prime(n):
    if n==1:
        return False
    for x in range(2,ceil(sqrt(n))):
        if  n%x==0:
            return  False
    return True


if __name__ == "__main__":
    assert is_prime(1) is False
    assert is_prime(2) is True
    assert is_prime(3) is True
    assert is_prime(4) is False
    assert is_prime(271) is True
    assert is_prime(272) is False
```

**Comment by aroberge** [comment]
Thank you; merci!  I do need to include `AssertionError` cases.
