### ISSUE TITLE
Exclude whole directory from tracebacks.

### ISSUE THREAD

**Issue by MrGreenTea** [aroberge/friendly#205]
**Is your feature request related to a problem? Please describe.**
We want to integrate this very lovely project into our product.
For this we make extensive use of `friendly.exclude_file_from_traceback` which works very well, but gets tedious because we have to include a lot of files because we want to hide internals from users by default.

**Describe the solution you'd like**
My idea would be to provide something like `friendly.exclude_directory_from_traceback`

**Describe alternatives you've considered**
The current alternative we are using is something like this:
```py
for f in pathlib.Path(dir).glob(**/*.py):
    friendly.exclude_file_from_traceback(f)
```

**Comment by aroberge** [comment]
Noted. I believe that I could implement something quickly. If I do, would you be able to test it from a cloned version of this repository, or would you need a new version uploaded from Pypi.org?

**Comment by hoefling** [comment]
@aroberge `pip install git+https://github.com/aroberge/friendly@some-branch-or-commit-hash-or-pull-request-ref` will do it nicely for tests.

**Comment by aroberge** [comment]
This has been implemented (https://github.com/aroberge/friendly/commit/0a568f7cc5d75ec1009f835c077c0ebfa34b5a13) and a quick test done to confirm that it **should** work.  I currently do not have the time to do more exhaustive tests. Please let me know if it does not work correctly.

**Comment by MrGreenTea** [comment]
installing from git does not work directly, as I get this error:
```
...
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "/tmp/pip-req-build-pv96twws/friendly/__init__.py", line 38, in <module>
      from . import editors_helpers
    File "/tmp/pip-req-build-pv96twws/friendly/editors_helpers.py", line 18, in <module>
      from .config import session
    File "/tmp/pip-req-build-pv96twws/friendly/config.py", line 7, in <module>
      from . import core
    File "/tmp/pip-req-build-pv96twws/friendly/core.py", line 19, in <module>
      from . import info_variables
    File "/tmp/pip-req-build-pv96twws/friendly/info_variables.py", line 10, in <module>
      from . import utils
    File "/tmp/pip-req-build-pv96twws/friendly/utils.py", line 9, in <module>
      import pure_eval
  ModuleNotFoundError: No module named 'pure_eval'
```

**Comment by hoefling** [comment]
@MrGreenTea yeah this comes from using `attr: friendly.__version__` when grabbing version metadata, so all the imports must be resolved on building. To mitigate, install the deps first and disable build isolation:
```sh
$ pip install pygments rich pure_eval wheel
$ pip install --no-build-isolation git+https://github.com/aroberge/friendly@master
```

**Comment by MrGreenTea** [comment]
@aroberge Thanks for the quick response. It works for me, but using `file.startswith` can lead to unexpected results:

Having a setup like this
```
├── modules
│   └── other.py
├── modules_2
│   └── second.py
└── test.py
```

with `test.py` like this:
```py
import friendly
import pathlib
import modules.other
import modules_2.second

friendly.exclude_directory_from_traceback(str(pathlib.Path(modules.other.__file__).parent.parent))

modules_2.second.function()
```

we will not get any traceback in `modules_2`.

What I ususally do to detect if a file is somewhere in the subtree of a directory is something like this:

```py
file = pathlib.Path("/home/me/test.txt")
dir = pathlib.Path("/home/me/")
if dir in file.parents:
    ...
```

This will not work well with symlinks, but better than `startswith`.

**Comment by aroberge** [comment]
I do not understand the problem in the example given. If you want to exclude only files from directory `modules`, you need to include one fewer `.parent` attribute.

**Comment by MrGreenTea** [comment]
> I do not understand the problem in the example given. If you want to exclude only files from directory `modules`, you need to include one fewer `.parent` attribute.

My bad, but it actually happens with the correct number of `.parent` too.

This is because the full `dir_name` that is added is `/tmp/testing/modules`. It works if I add the slash like this: `tmp/testing/modules/`.

**Comment by aroberge** [comment]
Ah, I see the problem. I should make sure that any excluded directory is stored with a string that ends with the path separator included.

**Comment by aroberge** [comment]
The problem should be fixed now.

Unrelated: I plan to add in the readme a list of projects or sites that use friendly. So far, I know that it is used in https://www.hackinscience.org/ and https://futurecoder.io/.  One of the main developers of IPython mentioned in  https://github.com/aroberge/friendly/issues/126 that he would consider ensuring that friendly is enabled by default in IPython when it is installed.  If you are interested, I could add a relevant link to your product in the readme.

**Comment by MrGreenTea** [comment]
> Ah, I see the problem. I should make sure that any excluded directory is stored with a string that ends with the path separator included.

Using `pathlib` would be nice as it would allow me to provide any `PathLike` to that function.
It's also more robust than using simple string manipulation.
If you want I can provide a PR for it.

**Comment by MrGreenTea** [comment]
> The problem should be fixed now.
> 
> Unrelated: I plan to add in the readme a list of projects or sites that use friendly. So far, I know that it is used in https://www.hackinscience.org/ and https://futurecoder.io/. One of the main developers of IPython mentioned in #126 that he would consider ensuring that friendly is enabled by default in IPython when it is installed. If you are interested, I could add a relevant link to your product in the readme.

Thanks for the offer, but it's an unfinished commercial product and would need to be cleared with our higher ups first, so I think we won't do it for now.

**Comment by MrGreenTea** [comment]
@aroberge Seems to work well for me. Would you be able to release a new version to pypi.org?

**Comment by aroberge** [comment]
Version 0.3.44 uploaded to Pypi

If you think it worthwhile, at any time after the release of your
commercial product, feel free to let me know so that I can include a link
in the readme.  While all my work is non-commercial and open source, I have
absolutely no hesitation in supporting those that make a living from
programming.

**Comment by hoefling** [comment]
@aroberge kudos to you for the fast, friendly and competent response! A rarity these days. The usage mentioning is on our list now, might be a matter of months though.

**Comment by aroberge** [comment]
> Using pathlib would be nice as it would allow me to provide any PathLike to that function.
It's also more robust than using simple string manipulation.
If you want I can provide a PR for it.

I'm going to leave this issue open for now. Based on this comment, I'm thinking of giving the option to either accepting a string or a pathlib Path object as an argument for both this function and the one to exclude a specific file, and doing the required conversion internally. No need to do a PR for it - I will take care of this myself.

**Comment by MrGreenTea** [comment]
> 
> 
> > Using pathlib would be nice as it would allow me to provide any PathLike to that function.
> > It's also more robust than using simple string manipulation.
> > If you want I can provide a PR for it.
> 
> I'm going to leave this issue open for now. Based on this comment, I'm thinking of giving the option to either accepting a string or a pathlib Path object as an argument for both this function and the one to exclude a specific file, and doing the required conversion internally. No need to do a PR for it - I will take care of this myself.

Thanks for the quick release and the work you do here! I already like it a lot :)

I have actually implemented a basic implementation of that already in #207.

**Comment by aroberge** [comment]
Thanks, I saw #207 and commented on it.

I need to put this aside for now and will try to come back to it tonight, or on the weekend.

**Comment by aroberge** [comment]
Note: I have not forgotten about this issue but have been focusing on PyCon.
