### ISSUE TITLE
Translate actual messages from Python

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly#209]
Currently, the answer to `what()` contains two parts:
```
SomeError: message from Python

Explanation of what SomeError means
```
The first part is not considered for translation; the second part is. It might be useful to consider making the original message translatable. This would likely affect how `explain()` works in order to have the translation of the message from Python appear, but ensuring that it does not appear twice when the message cannot be translated (either because English is selected or because a translation has not been created).

**Comment by sudosoph** [comment]
Hi! I just attended your lightning talk on this. Where do we modify the actual text? I have 2 more languages I can contribute for explanations. Thank you!

**Comment by ralle123** [comment]
i will do the spanish part

**Comment by aroberge** [comment]
Hi @sudosoph The translations are done using standard "gettext" tools.  You can find an explanation in the documentation: https://aroberge.github.io/friendly-traceback-docs/docs/html/translation_notes.html

Note that there are MANY strings to translate, and that this could be overwhelming to do by a single person - especially since I keep adding new content. However, it can be done little by little: the way that it works is that, if it cannot find a translation, it uses the English default (no exception raised).

Feel free to contact me at any time with questions or comments, either through github issues, or via email.

**Comment by aroberge** [comment]
@ralle123: see what I just wrote as a comment above.

**Comment by aroberge** [comment]
Moved to new project: https://github.com/friendly-traceback/friendly-traceback/issues/49
