### ISSUE TITLE
Using with the logging module.

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly#214]
During a recent PFPy meeting, a question has been raised about using with the logging module. Following a previous suggestion that was made to me during a PyConUS discussion, I was already planning to investigate capturing and processing `Warnings` with the logging module (https://docs.python.org/3/library/logging.html#logging.captureWarnings), thus enhancing friendly using the logging module.  However, I had not thought about the reverse, that is using friendly to supplement the logging module.

At the time, I mentioned that that this might simply require to use `friendly.install()`, but at the very least, I need to confirm this and add a section to the documentation. However, it might require more than this, for example, using the `redirect="capture"` option togther with some special function of the logging module. 

So, briefly:
1. figure out how to make friendly work with the logging module
2. add a section to the documentation.

**Comment by aroberge** [comment]
Here's a first example:
```python
import friendly
import logging

logging.basicConfig(filename="ignore.log")
friendly.set_lang('fr')

a = 1
b = 0
try:
    c = a / b
except Exception:
    friendly.explain_traceback(redirect="capture")
    result = friendly.get_output()
    logging.error(result)
```

And here's the output file
```
ERROR:root:
Traceback (most recent call last):
  File "ignore.py", line 10, in <module>
    c = a / b
ZeroDivisionError: division by zero

    Une exception de type `ZeroDivisionError` se produit lorsque vous essayez de diviser une valeur
    par zéro soit directement ou en utilisant une autre opération mathématique.
    
    Vous divisez par le terme suivant
    
         b
    
    qui est égal à zéro.
    
    Exception levée à la ligne 10 du fichier ignore.py.
    
        8: b = 0
        9: try:
    -->10:     c = a / b
                   ^^^^^
       11: except Exception:

            a:  1
            b:  0
```

**Comment by AlvesInfo** [comment]
génial, c'est tout à fait ça!
Mercii!!

**Comment by aroberge** [comment]
@AlvesInfo J'ai rajouté une section dans la documentation (en anglais) avec une explication supplémentaire qui pourrait être utile.
Le lien est le suivant: https://aroberge.github.io/friendly-traceback-docs/docs/html/usage.html#logging
