### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly#218]
Got this, so here's the report:
```
## Python exception

    :::pytb
    Traceback (most recent call last):
      File "solution.py", line 14, in <module>
        if len(list(range(i)))==9:
    MemoryError:

No information is known about this exception.
Please report this example to
https://github.com/aroberge/friendly/issues
```

It happen because hackinscience impose tight rlimits and the student provided with the following code:

```
the_list = [
    143266561,
    1738152473,
    312377936,
    1027708881,
    1495785517,
    1858250798,
    1693786723,
    1871655963,
    374455497,
    430158267,
]
for i in (the_list):
    if len(list(range(i)))==9:
        print(i)
```

The `if` line tries to computes `list(range(143266561))`...

It can be reproduced by using:
```
>>> from resource import setrlimit, RLIMIT_DATA
>>> setrlimit(RLIMIT_DATA, (4096, 4096))
>>> len(list(range(10000)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
```

**Comment by aroberge** [comment]
Merci!

I was wondering if I could ever test this ... I didn't know about the
resource module.

**Comment by JulienPalard** [comment]
You can test this by temporarily lowering the memory limit, (or by raising MemoryError yourself, the easy way...), like:

```
@contextmanager
def limited_memory(new_limit=536870912):
    """Temporarily lower available memory."""
    soft, hard = resource.getrlimit(resource.RLIMIT_DATA)
    resource.setrlimit(resource.RLIMIT_DATA, (new_limit, hard))
    yield
    resource.setrlimit(resource.RLIMIT_DATA, (soft, hard))
```

**Comment by JulienPalard** [comment]
I fine-tuned rlimit in hackinscience so the student code is a bit more restricted than the correction bots. Friendly being correction-bots side, it has a tad more memory than users now. I'm happy, thanks to this friendly is able to work even when the student has engulfed all the memory, see how great you spot the memory-consuming expression in this example:


## Exception Python


    :::pytb
    Traceback (most recent call last):
      File "check.py", line 993, in main
        from solution import dirichlet_square_solver
      File "CWD:/solution.py", line 24, in <module>
        len(list(range(100000000)))
    MemoryError:



Aucune information n’est disponible au sujet de cette exception.
Veuillez signaler cet exemple à
https://github.com/aroberge/friendly/issues

Si vous utilisez la console Friendly, utilisez `www()` pour
faire une recherche sur Internet pour ce cas particulier.



### L'exécution s'est arrêtée à la ligne 993 du fichier check.py



    :::text
           991:     to_test = 50
           992:     with checker.student_code():
        -->993:         from solution import dirichlet_square_solver
           994:     for i in range(to_test):



### Exception levée à la ligne 24 du fichier CWD:/solution.py.



    :::text
           22: import numpy as np
           23: 
        -->24: len(list(range(100000000)))
                   ^^^^^^^^^^^^^^^^^^^^^^



    :::text
        list:  <class list>
        range:  <class range>
        range(100000000):  range(0, 100000000)

**Comment by aroberge** [comment]
Interesting idea to have more memory correction side - of course, it makes sense. 

As you know, paths are shortened so we now see CWD (Current Working Directory); would it make sense to make this configurable so that one could add their own "short prefix". Currently, I have the following, based on the idea that friendly would be installed together with other packages in the "site-packages"  (or dist-packages on linux?) directory
```python
        if self.tests and path_lower.startswith(self.tests.lower()):
            path = "TESTS:" + path[len(self.tests) :]
        elif path_lower.startswith(self.friendly_path.lower()) and path_lower.endswith(
            "-packages"
        ):
            path = "INSTALLED:" + path[len(self.friendly_path) :]
            SITE_PACKAGES = self.friendly_path
        elif path_lower.startswith(self.cwd.lower()):
            path = "CWD:" + path[len(self.cwd) :]
        elif path_lower.startswith(self.python.lower()):
            path = "PYTHON_LIB:" + path[len(self.python) :]
        elif path_lower.startswith(self.home.lower()):
            path = "HOME:" + path[len(self.home) :]
        elif path.startswith("<ipython-input-"):
            parts = path.split("-")
            path = "[" + parts[-2] + "]"
        return path
```

I'm just about to add an explanation for what a Memory error is and include a test.  Of course, feel free to comment if you do not like the explanation I provide.

**Comment by aroberge** [comment]
The `resource` module is not available on Windows. So, I just included a test case where I explicitly raise a `MemoryError` and catch it.
