### ISSUE TITLE
TypeError: dict.update() argument after ** must be a mapping, not tuple

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly#221]
Looks like `set_cause_runtime` can get a pair of `None` from `get_likely_cause`, and then tries to update `self.info` (which is a dict) with this, giving a `TypeError`:

```
> friendly/core.py(409)set_cause_runtime()
-> cause = info_specific.get_likely_cause(
(Pdb) n
> friendly/core.py(412)set_cause_runtime()
-> self.info.update(**cause)
(Pdb) p cause
(None, None)
```

**To Reproduce**

I'm not able to consistently reproduce it yet, working on it.

**Comment by JulienPalard** [comment]
Can't reproduce this one after fixing https://github.com/aroberge/friendly/issues/222 ...

**Comment by aroberge** [comment]
It was a forgotten case from a major refactoring done a while ago.
