### ISSUE TITLE
formatting placeholder issue in attribute_error.py

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly#222]
**Describe the bug**
Looks like there's a formatting error in `def use_synonym`:

```
cause += _(
    "However, `{attr}` is an attribute of `{name}` with a similar meaning.\n"
).format(name=obj_name, attribute=attribute)
```

which should look like `.format(name=obj_name, attr=attribute)`

**Comment by aroberge** [comment]
That is embarrassing ... I will look into fixing this in a few hours.

**Comment by JulienPalard** [comment]
> That is embarrassing ...

Like we haven't all done it ¯\\_(ツ)_/¯
