### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly#225]
Hi André! Today a student reported this one:

```
## Python exception


    :::pytb
    Traceback (most recent call last):
      File "solution.py", line 6, in <module>
        assert is_prime(1) is False
    AssertionError:



No information is known about this exception.
Please report this example to
https://github.com/aroberge/friendly-traceback/issues

If you are using the Friendly console, use `www()` to
do an Internet search for this particular case.



### Exception raised on line 6 of file solution.py.



    :::text
           4: 
           5: if __name__ == "__main__":
        -->6:     assert is_prime(1) is False
           7:     assert is_prime(2) is True



    :::text
        is_prime: <function is_prime>
```

It think it may be a bit hackinscience-specific: not many newcomers do use `assert`?

It may be explained like:

> An `AssertionError` is raised when an `assert` statement is given a falsy expression. An `assert` statement is typically used to test something or to guarantee something is true before continuing.

**Comment by aroberge** [comment]
This is weird: I had included a fix for this a few days ago in https://github.com/aroberge/friendly/commit/090c1abec780cfff3e668e4c644f592679109f01. 
I had not included a unit test, which I will do. I will also change slightly the wording of the explanation I had provided.

**Comment by aroberge** [comment]
Made the changes mentioned above in commit https://github.com/aroberge/friendly/commit/5714349b191ae09fe986e4b806b6085967a174dd

Here's an example https://aroberge.github.io/friendly-traceback-docs/docs/html/tracebacks_en_3.9.html#assertionerror

I uploaded a new version to PyPI with this change.

**Comment by JulienPalard** [comment]
That's right! After an update 0.3.58 to 0.3.60 I got:

```
Dans Python, le mot clé assert est utilisé dans des énoncés ayant la forme assert condition, pour confirmer que condition n’est pas False; ni équivalente à False comme une liste vide, etc.
```

Merci !!
